apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: financial_rag
    user: rag
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: rag123
